import { QuestionBase } from '../question-base.model';
import { AbstractControl, FormArray, FormControl, FormGroup } from '@angular/forms';

export class NationaliteQuestion extends QuestionBase<string> {
  controlType = 'nationalite';
  pays = Object.keys(Pays);

  constructor(options: {} = {}) {
    super(options);
  }

  toFormControl(): AbstractControl {
    let group: any = {};

    group['apatride'] = new FormControl(false);
    group['pays'] = new FormArray([new FormControl()]);


    return new FormGroup(group, this.validators.concat(
      (control: AbstractControl) => {
        if (control.value['apatride'] !== true &&
            (!control.value['pays'] || (control.value['pays'] as []).filter(e => e !== null).length === 0)
        ) {
          return {'required': true}
        } else {
          return null;
        }
      }
    ));
  }

  get required() {
    return true;
  }
}

export enum Pays {
  CH = "ch",
  AF = "af",
  ZA = "za",
  AL = "al",
  DZ = "dz",
  DE = "de",
  AD = "ad",
  AO = "ao",
  AG = "ag",
  SA = "sa",
  AR = "ar",
  AM = "am",
  AU = "au",
  AT = "at",
  AZ = "az",
  BS = "bs",
  BH = "bh",
  BD = "bd",
  BB = "bb",
  BE = "be",
  BZ = "bz",
  BJ = "bj",
  BT = "bt",
  BY = "by",
  MM = "mm",
  BO = "bo",
  BA = "ba",
  BW = "bw",
  BR = "br",
  BN = "bn",
  BG = "bg",
  BF = "bf",
  BI = "bi",
  KH = "kh",
  CM = "cm",
  CA = "ca",
  CV = "cv",
  CL = "cl",
  CN = "cn",
  CY = "cy",
  CO = "co",
  KM = "km",
  CG = "cg",
  CD = "cd",
  KP = "kp",
  KR = "kr",
  CR = "cr",
  CI = "ci",
  HR = "hr",
  CU = "cu",
  DK = "dk",
  DJ = "dj",
  DM = "dm",
  EG = "eg",
  AE = "ae",
  EC = "ec",
  ER = "er",
  ES = "es",
  EE = "ee",
  US = "us",
  ET = "et",
  FJ = "fj",
  FI = "fi",
  FR = "fr",
  GA = "ga",
  GM = "gm",
  GE = "ge",
  GH = "gh",
  GR = "gr",
  GD = "gd",
  GT = "gt",
  GN = "gn",
  GW = "gw",
  GQ = "gq",
  GY = "gy",
  HT = "ht",
  HN = "hn",
  HU = "hu",
  CK = "ck",
  MH = "mh",
  SB = "sb",
  IN = "in",
  ID = "id",
  IQ = "iq",
  IR = "ir",
  IE = "ie",
  IS = "is",
  IL = "il",
  IT = "it",
  JM = "jm",
  JP = "jp",
  JO = "jo",
  KZ = "kz",
  KE = "ke",
  KG = "kg",
  KI = "ki",
  XK = "xk",
  KW = "kw",
  LA = "la",
  LS = "ls",
  LV = "lv",
  LB = "lb",
  LR = "lr",
  LY = "ly",
  LI = "li",
  LT = "lt",
  LU = "lu",
  MK = "mk",
  MG = "mg",
  MY = "my",
  MW = "mw",
  MV = "mv",
  ML = "ml",
  MT = "mt",
  MA = "ma",
  MU = "mu",
  MR = "mr",
  MX = "mx",
  FM = "fm",
  MD = "md",
  MC = "mc",
  MN = "mn",
  ME = "me",
  MZ = "mz",
  NA = "na",
  NR = "nr",
  NP = "np",
  NI = "ni",
  NE = "ne",
  NG = "ng",
  NO = "no",
  NZ = "nz",
  OM = "om",
  UG = "ug",
  UZ = "uz",
  PK = "pk",
  PW = "pw",
  PS = "ps",
  PA = "pa",
  PG = "pg",
  PY = "py",
  NL = "nl",
  PE = "pe",
  PH = "ph",
  PL = "pl",
  PT = "pt",
  QA = "qa",
  CF = "cf",
  DO = "do",
  RO = "ro",
  GB = "gb",
  RU = "ru",
  RW = "rw",
  LC = "lc",
  KN = "kn",
  SM = "sm",
  VC = "vc",
  SV = "sv",
  WS = "ws",
  ST = "st",
  SN = "sn",
  RS = "rs",
  SC = "sc",
  SL = "sl",
  SG = "sg",
  SK = "sk",
  SI = "si",
  SO = "so",
  SD = "sd",
  SS = "ss",
  LK = "lk",
  SE = "se",
  SR = "sr",
  SZ = "sz",
  SY = "sy",
  TJ = "tj",
  TW = "tw",
  TZ = "tz",
  TD = "td",
  CZ = "cz",
  TH = "th",
  TL = "tl",
  TG = "tg",
  TO = "to",
  TT = "tt",
  TN = "tn",
  TM = "tm",
  TR = "tr",
  TV = "tv",
  UA = "ua",
  UY = "uy",
  VU = "vu",
  VA = "va",
  VE = "ve",
  VN = "vn",
  YE = "ye",
  ZM = "zm",
  ZW = "zw"
}
