export enum Scolarite {
  SCOLARITE_OBLIGATOIRE  = 'SCOLARITE_OBLIGATOIRE',
  FORMATION_CONTINUE     = 'FORMATION_CONTINUE',
  FORMATION_DOCTORALE    = 'FORMATION_DOCTORALE',
  MAITRISE_UNIVERSITAIRE = 'MAITRISE_UNIVERSITAIRE',
  AUCUNE                 = "AUCUNE"
}
