export enum Scolarite {
  SCOLARITE_OBLIGATOIRE_1P_A_10P = 'SCOLARITE_OBLIGATOIRE_1P_A_10P',
  SCOLARITE_OBLIGATOIRE_11P      = 'SCOLARITE_OBLIGATOIRE_11P',
  FORMATION_DOCTORALE            = 'FORMATION_DOCTORALE',
  FORMATION_CONTINUE             = 'FORMATION_CONTINUE',
  AUCUNE                         = "AUCUNE",
  INCONNU                        = "INCONNU"
}
