social.tools:
  frontoffice:
    ihm-resource-location: classpath:/formulaire
    send-error-message: true

  editique.ws-location: ***REMOVED***
  qeli.matomo:
    server: ***REMOVED***
    site-id: 15

server:
  port: 8080

  servlet:
    context-path: /socialqeli_pub

  ssl:
    enabled: false

logging.level.root: INFO
