social.tools.frontoffice:
  ihm-resource-location: classpath:/formulaire

editique:
  ws-location: ***REMOVED***


server:
  port: 8080

  servlet:
    context-path: /socialqeli_pub

  ssl:
    enabled: false
