application.name: qeli-frontoffice

social.tools:
  frontoffice:
    ihm-resource-location: /formulaire
    ihm-context-path: /formulaire
    send-error-message: false

  qeli:
    min-years-from-now: 130
    max-enfants-a-charge: 20
    min-taux-activite-seul: 40
    min-taux-activite-avec-conjoint: 90
    limite-fortune: 4000
    limite-fortune-per-enfant: 2000
    limite-fortune-conjoint: 4000
    max-limite-fortune: 10000
    taxation-afc-years-from-now: 2
    heures-travail-par-semaine: 40
    deep-link-enabled: true
    api.pdf.enabled: true
    api.stats.enabled: true
    cookie-banner-enabled: true

spring:
  application.admin.enabled: false
  jmx.enabled: false

server:
  port: 443
  compression.enabled: true
  http2.enabled: true
  error.whitelabel.enabled: false

  servlet:
    context-path: /
    session.cookie:
      http-only: true
      secure: true

  max-http-header-size: 100KB

logging.level:
  root: INFO
