social.tools:
  frontoffice:
    ihm-resource-location: classpath:/formulaire
    send-error-message: true

  editique.ws-location: https://unServeurEditique/dialogue
  qeli:
    matomo.enabled: false
    cookie-banner-enabled: true

server:
  port: 8080
  servlet.context-path: /socialqeli_pub
  ssl.enabled: false
